Add Contributing md file
aaryan2134/JPMC-Quant-Challenge-2022 pull request #3
Opened 2022-10-10 19:26 UTC by amitkumar-y

Added the contributing md file, let me know if you want any change.

2022-10-10 19:44 UTC, aaryan2134 requested changes
Please make these changes for merging the request
Thank you for your effort

2022-10-10 19:44 UTC, aaryan2134 commented on CONTRIBUTING.md
> +11. Title the pull request with a short description of the changes you made and **request a review from a maintainer/reviewer**. For example, you can title an issue like so "Added John Doe to the pro
Please change the example to something which is more appropriate to the repository.

2022-10-10 19:44 UTC, aaryan2134 commented on CONTRIBUTING.md
> +  **Quora**: https://www.quora.com/profile/Aaryan-Arora-3 <br>
Please remove Quora from here

2022-10-10 19:44 UTC, aaryan2134 commented on CONTRIBUTING.md
> +### Our Responsibilities
Please remove this section

2022-10-10 19:44 UTC, aaryan2134 commented on CONTRIBUTING.md
> +
Please add a section on "What can you contribute?"
Which would include correcting any errors, missing information, solutions with explanations, links to online available solutions, etc

2022-10-11 17:01 UTC, amitkumar-y commented
Hi @aaryan2134 ,
I have incorporated the suggestions that you had provided, take a look at the updated Changes and let me know if you need any more changes.

2022-10-11 18:39 UTC, aaryan2134 commented
Great work. Thank you for contributing.

2022-10-11 18:40 UTC, merged